### ISSUE TITLE
Ruby support?

### ISSUE THREAD

**Issue by 9mm** [yioneko/nvim-yati#17]
Hey, I was wondering how hard it would be to add Ruby. For some reason it seems to be quite lacking with neovim from what I can see.

**Comment by yioneko** [comment]
Hi, #10 is my attempt to add Ruby support but has remained pending for a long time because I thought the [bundled Ruby plugin](https://github.com/vim-ruby/vim-ruby/blob/master/doc/ft-ruby-indent.txt) is already good enough in handling indent (not the one provided by nvim-treesitter), and there were some tough cases which I could not solve because of the undetermined behavior of Ruby ts parser when encountering syntax error and I myself didn't have a deep knowledge about the syntax and common coding style of Ruby.

I suggest trying the built-in indent plugin at first to see if it solves your problem. Simply disabling the indent module from nvim-treesitter and then it will come to effect.

**Comment by 9mm** [comment]
Interesting. Is there a way only to disable it for ruby, so I can use yati for everything else?

```
      yati = {
        enable = true,
        disable = {},
        default_lazy = true,
        default_fallback = 'auto',
      },
```

**Comment by yioneko** [comment]
The plugin won't be enabled for languages not supported, so your setup should already do the expected. You could also check it by `:set indentexpr?`, which should print `indentexpr=GetRubyIndent(v:lnum)` (the bundled Ruby indent function).

**Comment by 9mm** [comment]
Sorry I should have been more clear.

When I set `indent = true` for tree-sitter, ruby works fine. but everything else sucks.

When I set `ident = true` for yati, and `false` for regular tree-sitter, then everything else works better but ruby now breaks. Thats mostly why I was asking if you have ruby support because it seems to be "all or none"

It would be great to have everything with yati, including ruby, but you mentioned thats just a WIP now.

Ideally its everything else = yati, ruby = treesitter indent... not sure if thats possible.

I was hesitant to add that plugin you mentioned so I didnt have to disable `indent = true` for treesitter (or yati)

This is all quite confusing 💀

**Comment by yioneko** [comment]
Ok, sorry for my possibly confusing words, so it seems that the indent functionality from nvim-treesitter works fine? Then the ideal solution for you might be:
```lua

indent = {
  enable = true,
  disable = function(_, bufnr)
   -- disable indent module for ft except for ruby
    return vim.bo[bufnr].filetype ~= 'ruby'
  end,
},
yati = {
  enable = true,
}
```
Also you do not need to install the mentioned plugin before as it is bundled in vim by default. But if the above solution works for you, then just ignore this :)

**Comment by 9mm** [comment]
@yioneko awesome, that works!
