### ISSUE TITLE
Cython support

### ISSUE THREAD

**Issue by williamhCode** [yioneko/nvim-yati#6]
Could Cython support be added? A symlink would probably work `configs/python.lua -> cython.lua`

**Comment by williamhCode** [comment]
I tested that this does't work, I think nvim-treesitter has to add Cython support for this to work

**Comment by yioneko** [comment]
Hi, sorry for the late response, it seems that there is no support for Cython in upstream, and there might be no way to add support here. One workaround is to manually set `'filetype'` to 'python' using `:h ftdetect` but this will not always work since the syntax is not completely compatible and tree-sitter syntax for Cython is not available yet. Still recommend to use dedicated plugin for Cython (or similar langs) instead.

**Comment by williamhCode** [comment]
I see, thanks for the response!
